export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_SIGNUP_REQUEST = 'USER_LOGIN_FAILED'

export const LOAD_ASSETS_REQUEST = 'LOAD_ASSETS_REQUEST'
export const LOAD_ASSETS_SUCCESS = 'LOAD_ASSETS_SUCCESS'

export const UPDATE_TOKEN = 'UPDATE_TOKEN'
export const RESET_TOKEN = 'RESET_TOKEN'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'

