export const LOAD_USER_INFO_REQUEST = 'LOAD_USER_INFO_REQUEST';
export const LOAD_USER_INFO_SUCCESS = 'LOAD_USER_INFO_SUCCESS';
export const LOAD_USER_INFO_FAIL = 'LOAD_USER_INFO_FAIL';

export const LOAD_CAMPAIGN_LIST_REQUEST = 'LOAD_CAMPAIGN_LIST_REQUEST';
export const LOAD_CAMPAIGN_LIST_SUCCESS = 'LOAD_CAMPAIGN_LIST_REQUEST';
export const LOAD_CAMPAIGN_LIST_FAIL = 'LOAD_CAMPAIGN_LIST_REQUEST';

export const SCREEN_INDEX_SET = 'SCREEN_INDEX_SET';

export const REFRESH_VALUE = 'REFRESH_VALUE';
